### ISSUE TITLE
Buf External Libaray in Goland disappear

### ISSUE THREAD

**Issue by luoyanzecs** [bufbuild/intellij-buf#237]
Goland Version : 2024.1.4
Buf plugin Version : 0.4.1

Buf External Libaray in Goland disappear after updating Goland.

![image](https://github.com/bufbuild/intellij-buf/assets/44136414/daf7efe6-55d3-40d0-83eb-f0db7983a6e7)

Import link is not working.

![image](https://github.com/bufbuild/intellij-buf/assets/44136414/d1d49fdb-3b9b-4332-a62f-a4247af2e592)

Its inconvenient to use.

**Comment by pkwarren** [comment]
I'm not able to reproduce this behavior locally with GoLand 2024.1.4 and the Buf 0.4.1 plugin. Can you see if there are any errors for `build.buf` in the IDE log file (on a Mac, I can see where this file is found by going to `Help -> Show Log in Finder`).

It would also be good to ensure that the path to the Buf CLI is set properly under `Settings -> Tools -> Buf`.

The plugin determines which external libraries are present by scanning the `buf.lock` file(s) in your project. It would also help to try and debug if you could provide the contents of these files.

Thanks!

**Comment by luoyanzecs** [comment]
I find some logs in WARN level and no log in Error level. And my OS is windows10.

```
2024-06-26 09:58:17,669 [   5141]   WARN - #c.i.i.s.i.StartupManagerImpl - Migrate build.buf.intellij.resolve.RefreshAdditionalBufRoots to ProjectActivity [Plugin: com.github.bufbuild.intellij]
com.intellij.diagnostic.PluginException: Migrate build.buf.intellij.resolve.RefreshAdditionalBufRoots to ProjectActivity [Plugin: com.github.bufbuild.intellij]
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.kt:276)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runPostStartupActivities(StartupManagerImpl.kt:68)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$3$2.invokeSuspend(StartupManagerImpl.kt:191)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$3$2.invoke(StartupManagerImpl.kt)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$3$2.invoke(StartupManagerImpl.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$3.invokeSuspend(StartupManagerImpl.kt:190)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

2024-06-26 10:01:10,595 [ 178067]   INFO - #build.buf.intellij.annotator.BufAnalyzeUtils - Ran buf lint in 2125ms

2024-06-26 10:03:16,430 [ 303902]   INFO - #build.buf.intellij.annotator.BufAnalyzeUtils - Ran buf lint in 2345ms

2024-06-26 10:10:05,943 [   7237]   WARN - #c.i.i.s.i.StartupManagerImpl - Migrate build.buf.intellij.resolve.RefreshAdditionalBufRoots to ProjectActivity [Plugin: com.github.bufbuild.intellij]
com.intellij.diagnostic.PluginException: Migrate build.buf.intellij.resolve.RefreshAdditionalBufRoots to ProjectActivity [Plugin: com.github.bufbuild.intellij]
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.kt:276)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runPostStartupActivities(StartupManagerImpl.kt:68)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$3$2.invokeSuspend(StartupManagerImpl.kt:191)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$3$2.invoke(StartupManagerImpl.kt)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$3$2.invoke(StartupManagerImpl.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$3.invokeSuspend(StartupManagerImpl.kt:190)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)


2024-06-26 10:10:45,930 [  47224]   WARN - #c.i.i.s.i.StartupManagerImpl - Migrate build.buf.intellij.resolve.RefreshAdditionalBufRoots to ProjectActivity [Plugin: com.github.bufbuild.intellij]
com.intellij.diagnostic.PluginException: Migrate build.buf.intellij.resolve.RefreshAdditionalBufRoots to ProjectActivity [Plugin: com.github.bufbuild.intellij]
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.kt:276)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runPostStartupActivities(StartupManagerImpl.kt:68)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$3$2.invokeSuspend(StartupManagerImpl.kt:191)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$3$2.invoke(StartupManagerImpl.kt)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$3$2.invoke(StartupManagerImpl.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$3.invokeSuspend(StartupManagerImpl.kt:190)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:270)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

```

buf plugin setting:
![image](https://github.com/bufbuild/intellij-buf/assets/44136414/92230fff-1908-4ebb-a240-fb603f3dda75)

bufcli verison: 
```
PS C:\Program Files\Go\bin> .\buf.exe --version
1.29.0
```

buf.yaml
```
version: v1
name: buf.build/luoyanzecs/petservice
breaking:
  use:
    - FILE
deps:
  - buf.build/googleapis/googleapis
lint:
  use:
    - DEFAULT
```

buf.lock
```
# Generated by buf. DO NOT EDIT.
version: v1
deps:
  - remote: buf.build
    owner: googleapis
    repository: googleapis
    commit: f0e53af8f2fc4556b94f482688b57223
    digest: shake256:de26a277fc28b8b411ecf58729d78d32fcf15090ffd998a4469225b17889bfb51442eaab04bb7a8d88d203ecdf0a9febd4ffd52c18ed1c2229160c7bd353ca95
```

**Comment by luoyanzecs** [comment]
@pkwarren I try to upgrade bufcli to v1.34.0 and it worked!!!

Maybe some unexpected  wrong happend with bufcli v1.29.0 & intellij-buf plugin v0.4.1 .

Thanks!
