### ISSUE TITLE
Support using Buf binary in WSL

### ISSUE THREAD

**Issue by F21** [bufbuild/intellij-buf#288]
I am using intellij with the buf plugin on Windows 11. I use WSL in Windows terminal as my terminal and all my CLI tools run in WSL.

In the buf plugin, I configured it to use the Buf binary in WSL: `\\wsl.localhost\Ubuntu\usr\local\bin\buf`. This causes an error when I attempt to use buf to reformat my protobuf: 
```
com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "\\wsl.localhost\Ubuntu\usr\local\bin\buf" (in directory "C:\Work\project"): CreateProcess error=193, %1 is not a valid Win32 application
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:384)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:85)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:45)
	at com.intellij.execution.process.KillableProcessHandler.<init>(KillableProcessHandler.java:41)
	at com.intellij.execution.process.ColoredProcessHandler.<init>(ColoredProcessHandler.java:23)
	at com.intellij.execution.process.ScriptRunnerUtil.lambda$execute$2(ScriptRunnerUtil.java:77)
	at com.intellij.execution.process.ScriptRunnerUtil.execute(ScriptRunnerUtil.java:142)
	at com.intellij.execution.process.ScriptRunnerUtil.execute(ScriptRunnerUtil.java:100)
	at com.intellij.execution.process.ScriptRunnerUtil.execute(ScriptRunnerUtil.java:77)
	at build.buf.intellij.annotator.BufAnalyzeUtils$runBufCommand$2.invokeSuspend(BufAnalyzeUtils.kt:210)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.SoftLimitedDispatcher$Worker.run(SoftLimitedDispatcher.kt:125)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
Caused by: java.io.IOException: Cannot run program "\\wsl.localhost\Ubuntu\usr\local\bin\buf" (in directory "D:\14-Workspace\Boostport\iam"): CreateProcess error=193, %1 is not a valid Win32 application
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1170)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1089)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:463)
	at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:469)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:374)
	... 17 more
Caused by: java.io.IOException: CreateProcess error=193, %1 is not a valid Win32 application
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:500)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:159)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1126)
	... 21 more
```
In addition, it is also not able to detect imported buf protos (such as `"buf/validate/validate.proto"`) correctly.

I think it would be really neat if the plugin can support WSL as a lot of Windows users use WSL for their tools.

**Comment by F21** [comment]
hey @stefanvanburen , after updating to the latest version of buf (1.65.0) and v0.7.0 of the intellij plugin, I am not getting this error when using the plugin to reformat my protobuf:
```
com.intellij.execution.process.ProcessNotCreatedException: Couldn't run In "C:\\Work\\repo" execute /usr/local/bin/buf format proto/test/v1/test.proto: 2: No such file or directory (os error 2)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:421)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:85)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:45)
	at com.intellij.execution.process.KillableProcessHandler.<init>(KillableProcessHandler.java:40)
	at com.intellij.execution.process.ColoredProcessHandler.<init>(ColoredProcessHandler.java:27)
	at com.intellij.execution.process.ScriptRunnerUtil.lambda$execute$2(ScriptRunnerUtil.java:76)
	at com.intellij.execution.process.ScriptRunnerUtil.execute(ScriptRunnerUtil.java:138)
	at com.intellij.execution.process.ScriptRunnerUtil.execute(ScriptRunnerUtil.java:97)
	at com.intellij.execution.process.ScriptRunnerUtil.execute(ScriptRunnerUtil.java:76)
	at build.buf.intellij.annotator.BufAnalyzeUtils$runBufCommand$2.invokeSuspend(BufAnalyzeUtils.kt:210)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:34)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.SoftLimitedDispatcher$Worker.run(SoftLimitedDispatcher.kt:130)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:610)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:1188)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:775)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:762)
Caused by: com.intellij.platform.eel.ExecuteProcessException: Couldn't run In "C:\\Work\\repo" execute /usr/local/bin/buf format proto/test/v1/test.proto: 2: No such file or directory (os error 2)
	at com.intellij.platform.ijent.impl.GrpcIjentChildProcessKt.handleMessageFromProcess(GrpcIjentChildProcess.kt:480)
	at com.intellij.platform.ijent.impl.GrpcIjentChildProcessKt.access$handleMessageFromProcess(GrpcIjentChildProcess.kt:1)
	at com.intellij.platform.ijent.impl.GrpcIjentChildProcessKt$initializeCoroutineScopeAndJobs$2$2$1$1$1.invokeSuspend(GrpcIjentChildProcess.kt:308)
	at com.intellij.platform.ijent.impl.GrpcIjentChildProcessKt$initializeCoroutineScopeAndJobs$2$2$1$1$1.invoke(GrpcIjentChildProcess.kt)
	at com.intellij.platform.ijent.impl.GrpcIjentChildProcessKt$initializeCoroutineScopeAndJobs$2$2$1$1$1.invoke(GrpcIjentChildProcess.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:44)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:166)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.platform.ijent.impl.GrpcIjentChildProcessKt$initializeCoroutineScopeAndJobs$2$2$1$1.emit(GrpcIjentChildProcess.kt:307)
	at com.intellij.platform.ijent.impl.GrpcIjentChildProcessKt$initializeCoroutineScopeAndJobs$2$2$1$1.emit(GrpcIjentChildProcess.kt:306)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:11)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:11)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:115)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:84)
	at io.grpc.kotlin.ClientCalls$rpcImpl$1$1.invokeSuspend(ClientCalls.kt:325)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:34)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at com.intellij.platform.ijent.spi.IjentThreadPool$IjentThreadFactory$newThread$thread$1.run(IjentThreadPool.kt:68)

```

**Comment by F21** [comment]
Imported protos seem to work correctly now, so it's just the formatting that's not working for me.

**Comment by F21** [comment]
Thanks for working on this @stefanvanburen ! I upgraded buf to `v1.65.0` and the plugin to `v0.7.2`. Using `Code -> Reformat Code` works correctly, but I am getting this error from the buf plugin regarding the LSP:
```
com.intellij.execution.process.ProcessNotCreatedException: Couldn't run In "C:\\Work\\project" execute /usr/local/bin/buf lsp serve --log-format=text: 2: No such file or directory (os error 2)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:421)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:85)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:45)
	at com.intellij.platform.lsp.api.LspServerDescriptor$startServerProcess$1.<init>(LspServerDescriptor.kt:110)
	at com.intellij.platform.lsp.api.LspServerDescriptor.startServerProcess(LspServerDescriptor.kt:110)
	at com.intellij.platform.lsp.impl.connector.Lsp4jServerConnectorStdio.<init>(Lsp4jServerConnectorStdio.kt:17)
	at com.intellij.platform.lsp.impl.LspServerImpl.n(LspServerImpl.kt:446)
	at com.intellij.platform.lsp.impl.LspServerImpl.n(LspServerImpl.kt:411)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:334)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at com.intellij.util.concurrency.ContextCallable.lambda$call$1(ContextCallable.java:86)
	at com.intellij.concurrency.ThreadContext.installThreadContext(threadContext.kt:305)
	at com.intellij.util.concurrency.ContextCallable.lambda$call$2(ContextCallable.java:83)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:96)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:167)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:167)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:173)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:167)
	at com.intellij.util.concurrency.ContextRunnable.lambda$run$0(ContextRunnable.java:26)
	at com.intellij.concurrency.ThreadContext.resetThreadContext(threadContext.kt:294)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:25)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: com.intellij.platform.eel.ExecuteProcessException: Couldn't run In "C:\\Work\\project" execute /usr/local/bin/buf lsp serve --log-format=text: 2: No such file or directory (os error 2)
	at com.intellij.platform.ijent.impl.GrpcIjentChildProcessKt.handleMessageFromProcess(GrpcIjentChildProcess.kt:480)
	at com.intellij.platform.ijent.impl.GrpcIjentChildProcessKt.access$handleMessageFromProcess(GrpcIjentChildProcess.kt:1)
	at com.intellij.platform.ijent.impl.GrpcIjentChildProcessKt$initializeCoroutineScopeAndJobs$2$2$1$1$1.invokeSuspend(GrpcIjentChildProcess.kt:308)
	at com.intellij.platform.ijent.impl.GrpcIjentChildProcessKt$initializeCoroutineScopeAndJobs$2$2$1$1$1.invoke(GrpcIjentChildProcess.kt)
	at com.intellij.platform.ijent.impl.GrpcIjentChildProcessKt$initializeCoroutineScopeAndJobs$2$2$1$1$1.invoke(GrpcIjentChildProcess.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:44)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:166)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.platform.ijent.impl.GrpcIjentChildProcessKt$initializeCoroutineScopeAndJobs$2$2$1$1.emit(GrpcIjentChildProcess.kt:307)
	at com.intellij.platform.ijent.impl.GrpcIjentChildProcessKt$initializeCoroutineScopeAndJobs$2$2$1$1.emit(GrpcIjentChildProcess.kt:306)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:11)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:11)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:115)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:84)
	at io.grpc.kotlin.ClientCalls$rpcImpl$1$1.invokeSuspend(ClientCalls.kt:325)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:34)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at com.intellij.platform.ijent.spi.IjentThreadPool$IjentThreadFactory$newThread$thread$1.run(IjentThreadPool.kt:68)

```

**Comment by F21** [comment]
@stefanvanburen , I upgraded to v0.7.6 and code formatting works perfectly. However, this error is still popping up in the IDE:

```
java.lang.Throwable: Synchronous execution under ReadAction: C:\WINDOWS\system32\wsl.exe --distribution Ubuntu --exec pwd, see com.intellij.execution.process.OSProcessHandler#checkEdtAndReadAction() Javadoc for resolutions
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:375)
	at com.intellij.execution.process.OSProcessHandler.checkEdtAndReadAction(OSProcessHandler.java:165)
	at com.intellij.execution.process.OSProcessHandler.waitFor(OSProcessHandler.java:102)
	at com.intellij.execution.process.CapturingProcessRunner.runProcess(CapturingProcessRunner.java:62)
	at com.intellij.execution.process.CapturingProcessRunner.runProcess(CapturingProcessRunner.java:51)
	at com.intellij.execution.process.CapturingProcessHandler.runProcess(CapturingProcessHandler.java:57)
	at com.intellij.execution.wsl.WslDistributionDescriptor.readWslOutput(WslDistributionDescriptor.java:199)
	at com.intellij.execution.wsl.WslDistributionDescriptor.readWslOutputLine(WslDistributionDescriptor.java:178)
	at com.intellij.execution.wsl.WslDistributionDescriptor.computeMntRoot(WslDistributionDescriptor.java:156)
	at com.intellij.execution.wsl.WslDistributionDescriptor.lambda$new$0(WslDistributionDescriptor.java:57)
	at com.intellij.execution.wsl.WslDistributionDescriptor.executeOrRunTask(WslDistributionDescriptor.java:227)
	at com.intellij.execution.wsl.WslDistributionDescriptor.lambda$new$1(WslDistributionDescriptor.java:57)
	at com.intellij.execution.wsl.WslDistributionDescriptor$2.compute(WslDistributionDescriptor.java:243)
	at com.intellij.openapi.util.ClearableLazyValue.getValue(ClearableLazyValue.java:43)
	at com.intellij.execution.wsl.WslDistributionDescriptor$2.getValue(WslDistributionDescriptor.java:253)
	at com.intellij.execution.wsl.WslDistributionDescriptor.getMntRoot(WslDistributionDescriptor.java:135)
	at com.intellij.execution.wsl.WSLDistribution.getMntRoot(WSLDistribution.java:638)
	at com.intellij.execution.wsl.WSLDistribution.getWslPath(WSLDistribution.java:629)
	at build.buf.intellij.lsp.BufLspServerDescriptor.getFileUri(BufLspServerDescriptor.kt:112)
	at com.intellij.platform.lsp.impl.LspServerImpl.getDocumentIdentifier(LspServerImpl.kt:159)
	at com.intellij.platform.lsp.impl.intention.LspIntentionActionService.getIntentionActions(LspIntentionActionService.kt:82)
	at com.intellij.platform.lsp.impl.intention.LspIntentionActionWrapper.T(LspIntentionActionWrapper.kt:26)
	at com.intellij.platform.lsp.impl.intention.LspIntentionActionWrapper.isAvailable(LspIntentionActionWrapper.kt:19)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler$Companion.availableFor(ShowIntentionActionsHandler.kt:153)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.availableFor(ShowIntentionActionsHandler.kt)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.lambda$getRegisteredIntentionActions$6(ShowIntentionsPass.java:393)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler$Companion.chooseBetweenHostAndInjected(ShowIntentionActionsHandler.kt:216)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseBetweenHostAndInjected(ShowIntentionActionsHandler.kt)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getRegisteredIntentionActions(ShowIntentionsPass.java:392)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:364)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.doCollectInformation(ShowIntentionsPass.java:262)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:76)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:449)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:29)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$3(PassExecutorService.java:445)
	at com.intellij.openapi.application.impl.AppImplKt$runnableUnitFunction$1.invoke(appImpl.kt:124)
	at com.intellij.openapi.application.impl.AppImplKt$runnableUnitFunction$1.invoke(appImpl.kt:124)
	at com.intellij.platform.locking.impl.NestedLocksThreadingSupport.tryRunReadAction(NestedLocksThreadingSupport.kt:900)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1266)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$4(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$14(CoreProgressManager.java:744)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:819)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:775)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:743)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:434)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:409)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.cacheFileTypesInside(FileTypeManagerImpl.java:904)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$1(PassExecutorService.java:409)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:306)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:407)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:289)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:511)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1450)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2019)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)

```
Note: Code formatting still works after this error showed up.

**Comment by stefanvanburen** [comment]
hi @F21, just published [0.7.7](https://github.com/bufbuild/intellij-buf/releases/tag/v0.7.7) to hopefully fix that; should be published to the JetBrains Marketplace in the next couple days!

**Comment by stefanvanburen** [comment]
@F21 glad to hear that, and thanks again for the patience as we debugged this issue!
